### ISSUE TITLE
Binary build with nodejs lts (v14.15.3) fails on Windows

### ISSUE THREAD

**Issue by asamuzaK** [mongodb-js/boxednode#12]
Build fails when creating a binary with nodejs lts (currently v14.15.3) on Windows.

[Job log](https://github.com/asamuzaK/withExEditorHost/runs/1639463349?check_suite_focus=true#step:7:414)

The build was successful until v14.15.1.
There seems to be some fixes in vcbuild.bat between v14.15.1 and v14.15.3.

[Comparing v14.15.1...v14.15.3 · nodejs/node](https://github.com/nodejs/node/compare/v14.15.1...v14.15.3#diff-67745f8cde46d0a81ee94d49f2a7db1dd7aad869d8cdb0aca44ef60d127b431e)

**Comment by addaleax** [comment]
I could not reproduce this locally -- I've opened https://github.com/mongodb-js/boxednode/pull/13, if this is something that's specific to github actions, it might let us know.

**Comment by asamuzaK** [comment]
After many failures, I was finally able to build it successfully.
[Job log](https://github.com/asamuzaK/withExEditorHost/runs/1672330224?check_suite_focus=true)

I was using bash on Windows as well in my github workflow, but when I changed shell to cmd, it worked.
I don't know why it used to succeed with bash before and now it doesn't, but anyway, I will close this issue as invalid.

Thanks

**Comment by asamuzaK** [comment]
Thank you for the information.
I will test with the new version and let you know the result.
Maybe this weekend.

**Comment by asamuzaK** [comment]
Verified. [Job log](https://github.com/asamuzaK/withExEditorHost/runs/2100078000?check_suite_focus=true)
