### ISSUE TITLE
[Question] is there any way to make the process faster?

### ISSUE THREAD

**Issue by saostad** [mongodb-js/boxednode#15]
Hi, 
thanks for the package.
I have windows 10 laptop with 32GB of Ram, CPU Core i7 - 8750H, and SSD disk, but it takes forever to compile the .exe file for me. 
is there any way to make the process faster?

**Comment by addaleax** [comment]
I don't think there's anything you can do that's specific to boxednode. You might be able to use a caching compiler, I know there's options for that also for cl.exe (the Windows compiler that boxednode uses).

**Comment by jeffrson** [comment]
@addaleax 
Now when there's a compiled binary node, how can it be used in subsequent packaging tries (after changing the source) without unpacking nodes' source and going through all the make steps again and again?

**Comment by addaleax** [comment]
@jeffrson If you’re on the same machine, or cache the compilation directory, then I think this should work fine (except maybe on Windows). If there’s some specific problem, feel free to open a new ticket :)

**Comment by jeffrson** [comment]
Yes, this is on Windows. So I will try to run it on Linux and compare. Thanks!
