### ISSUE TITLE
Use `@pkgjs/nv` for version resolution

### ISSUE THREAD

**Issue by wesleytodd** [mongodb-js/boxednode#5]
Would you be interested in using this package to do the resolution?  It supports semver ranges like you have, but also all of the [aliases the Package Maintenance Team is working to standardize on](https://github.com/nodejs/package-maintenance/issues/236#issue-474783582).

https://github.com/pkgjs/nv/

**Comment by addaleax** [comment]
Yeah, that sounds like something that would make sense. Do you want to submit a PR? :slightly_smiling_face:

**Comment by wesleytodd** [comment]
Sure thing, 🤞 that I can quickly and that it works alright in TypeScript projects.
